name: Deploy CampusTalk to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # === 1️⃣ Checkout Code ===
      - name: Checkout Code
        uses: actions/checkout@v4

      # === 2️⃣ Build Vite Frontend ===
      - name: Build Frontend (Vite)
        working-directory: FrontEnd
        run: |
          npm ci
          npm run build
          echo "✅ Frontend build completed."

      # === 3️⃣ Build Spring Boot Backend ===
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Spring Boot Backend
        working-directory: BackEnd/campusTalk
        run: |
          ./mvnw clean package -DskipTests
          echo "✅ Backend build completed."

      # === 4️⃣ Rename built JAR (for uploading) ===
      - name: Copy JAR to root for deploy
        run: |
          cp BackEnd/campusTalk/target/*.jar ./campustalk-backend.jar
          ls -lh campustalk-backend.jar
          echo "✅ Backend JAR ready."

      # === 5️⃣ Upload Frontend + Backend to EC2 ===
      - name: Upload files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          source: "campustalk-backend.jar,FrontEnd/dist/**"
          target: /home/ubuntu/campustalk-deploy-temp/

      # === 6️⃣ Run deployment commands (systemd + nginx) ===
      - name: Restart Backend & Deploy Frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            set -e

            echo "🔹 Moving backend JAR to deployment directory..."
            sudo mv /home/ubuntu/campustalk-deploy-temp/campustalk-backend.jar ${{ secrets.EC2_BACKEND_DIR }}/campustalk-backend.jar
            sudo chown ubuntu:ubuntu ${{ secrets.EC2_BACKEND_DIR }}/campustalk-backend.jar

            echo "🔹 Restarting CampusTalk backend (port 8081)..."
            sudo systemctl daemon-reload
            sudo systemctl restart campustalk-backend.service
            sudo systemctl status campustalk-backend.service --no-pager -l

            echo "🔹 Deploying frontend to Nginx directory..."
            sudo rm -rf ${{ secrets.EC2_FRONTEND_DIR }}/*
            sudo cp -r /home/ubuntu/campustalk-deploy-temp/FrontEnd/dist/* ${{ secrets.EC2_FRONTEND_DIR }}/
            sudo chown -R www-data:www-data ${{ secrets.EC2_FRONTEND_DIR }}

            echo "🔹 Reloading Nginx..."
            sudo systemctl reload nginx

            echo "🎉 Deployment completed successfully!"
is this 
